# primarily client side
DISPLAY_WIDTH, DISPLAY_HEIGHT = 1080, 720
SCREEN_WIDTH, SCREEN_HEIGHT = 400, 300
FONT_SIZE = 32
LARGE_FONT_SIZE = 128
TRACK_LIFETIME = 4
TRACK_INTERVAL = 20

# primarily server side
BUFF_SIZE = 1024
ROUND_INTERVAL = 5
WAITING_TIME = ROUND_INTERVAL

