name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u joonsey --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/joonsey/ptanks/server:latest .
          docker push ghcr.io/joonsey/ptanks/server:latest


